vars:
  - models:
      - standard-rf-classifier
      - drf-weighted-classifier
#      - ensemble-weighted-classifier
#      - diversity-effect-weighted-classifier
  - datasets:
      - mnist_subset
      - cover
#      - digits

stages:

  train:
    matrix:
      model: ${models}
      dataset: ${datasets}
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl

  plot_staged_errors:
    cmd: python ../../plot_staged_errors.py
    deps:
      - results
      - ../../plot_staged_errors.py
    outs:
      - plots/staged_errors/

  plot_ambiguity_decomp:
    cmd: python ../../plot_ambiguity_decomp.py
    deps:
      - decomps
      - ../../plot_ambiguity_decomp.py
    outs:
      - plots/ambiguity_decomp

#  get_staged_errors:
#    matrix:
#      model: ${models}
#      dataset: ${datasets}
#    cmd: python ../../get_staged_errors.py --model ${item.model} --dataset ${item.dataset}
#    deps:
#      - ../../get_staged_errors.py
#      - results/${item.dataset}/${item.model}.pkl
#    outs:
#      - staged_errors/${item.dataset}/${item.model}.json
#
#  combine_metrics:
#    foreach: ${datasets}
#    do:
#      cmd: python ../../combine_metrics.py --dataset ${item}
#      deps:
#        - ../../combine_metrics.py
#        - staged_errors/${item}
##      outs:
##        - staged_errors/${item}-combined.json
#      plots:
#        - staged_errors/${item}-combined.json:
#            template: ../../staged_errors_template.json
#            x: member_idx
#            y: error
#
#plots:
#  - staged_errors/cover-combined.json:
#      template: ../../staged_errors_template.json
#      x: member_idx
#      y: error
#  - staged_errors/digits-combined.json:
#      template: ../../staged_errors_template.json
#      x: member_idx
#      y: error
