#file: noinspection YAMLSchemaValidation
vars:
  - models:
      - standard_rf
      - drf_weighted_bootstrap
      - drf_weighted_fit
      - xu_chen
      - capped_sigmoid
      - capped_lerped_sigmoid
#      - ensemble-weighted-classifier
#      - diversity-effect-weighted-classifier
  - slow_models:  # TODO
      - dynamic_threshold
      - drf_weighted_fit_oob
  - small_datasets:
      - qsar-biodeg
      - diabetes
  - medium_datasets:
      - digits
      - bioresponse
      - spambase-openml
  - large_datasets:
      - mnist_subset
      - cover

stages:


  # okay so my "good drf" thing is *not* a special case of binary with fixed threshold at 1/2
  # so we can't kill two birds with one stone here
  # -- evaluating with fixed threshold most likely only makes sense on binary classification problems since
  # equivalence (correct/incorrect) is not given there
  # -- evaluating with dynamic threshold is also different for binary, should evaluate these on all datasets


  train_small:
    matrix:
      model: ${models}
      dataset: ${small_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_small:
    matrix:
      model: ${models}
      dataset: ${small_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  train_medium:
    matrix:
      model: ${models}
      dataset: ${medium_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_medium:
    matrix:
      model: ${models}
      dataset: ${medium_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  train_large:
    matrix:
      model: ${models}
      dataset: ${large_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_large:
    matrix:
      model: ${models}
      dataset: ${large_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/


  train_slow_small:
    matrix:
      model: ${slow_models}
      dataset: ${small_datasets}
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl


  get_staged_decomp_values_slow_small:
    matrix:
      model: ${slow_models}
      dataset: ${small_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  plot_bvd_decomps:
    cmd: python ../../plot_bvd.py
    deps:
      - staged-decomp-values
      - ../../plot_bvd.py
      - ../../../decompose/plot_decomp_grid.py
    outs:
      - plots/bvd-decomps/plot_bvd_drf
      - plots/bvd-decomps/plot_bvd_standard_rf

# TODO re-enable
#  plot_ens_decomps:
#    cmd: python ../../plot_ens.py
#    deps:
#      - staged-decomp-values
#      - ../../plot_ens.py
#    outs:
#      - plots/bvd-decomps/ens.png

# TODO add plot_err_div

# TODO maybe re-enable
# just because im too tired to wait, re-enable
#  plot_compare_models:
#    matrix:
#      dataset: ${all_datasets}
#    cmd: python ../../plot_compare_models.py --dataset ${item.dataset}
#    deps:
#      - staged-decomp-values
#      - ../../plot_compare_models.py
#    outs:
#      - plots/bvd-decomps/${item.dataset}/


