#file: noinspection YAMLSchemaValidation
vars:
  - small_datasets:
      - qsar-biodeg
      - diabetes
  - models_for_small:
      - ce-nn
  - models:
      - standard-rf-classifier
      - drf-weighted-bootstrap-classifier
      - drf-weighted-fit-classifier
      - drf-weighted-fit-oob-classifier
#      - ensemble-weighted-classifier
#      - diversity-effect-weighted-classifier
  - datasets:  # roughly in order of size
      # small
      - qsar-biodeg
      - diabetes
      # medium
      - digits
      - bioresponse
      - spambase-openml
      - mnist_subset
      # large
      - cover

stages:

  train_small:
    matrix:
      model: ${models_for_small}
      dataset: ${small_datasets}
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  # leave this stage name unchanged to not discard the results
#  train:
#    matrix:
#      model: ${models}
#      dataset: ${datasets}
#    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
#    deps:
#      - ../../run_bvd.py
#    params:
#      - params.yaml:
#    outs:
#      - results/${item.dataset}/${item.model}.pkl
#      - decomps/${item.dataset}/${item.model}.pkl

# deprecated, to be replaced with things from get_staged_decomp_values
#  plot_staged_errors:
#    cmd: python ../../plot_staged_errors.py
#    deps:
#      - results
#      - ../../plot_staged_errors.py
#    outs:
#      - plots/staged_errors/

  get_staged_decomp_values:
    matrix:
      model: ${models}
      dataset: ${datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  plot_bvd_decomps:
    cmd: python ../../plot_bvd.py
    deps:
      - staged-decomp-values
      - ../../plot_bvd.py
    outs:
      - plots/bvd-decomps/bvd.png

  plot_ens_decomps:
    cmd: python ../../plot_ens.py
    deps:
      - staged-decomp-values
      - ../../plot_ens.py
    outs:
      - plots/bvd-decomps/ens.png

  plot_compare_models:
    matrix:
      dataset: ${datasets}
    cmd: python ../../plot_compare_models.py --dataset ${item.dataset}
    deps:
      - staged-decomp-values
      - ../../plot_compare_models.py
    outs:
      - plots/bvd-decomps/${item.dataset}/
#
#  plot_ambiguity_decomp:
#    cmd: python ../../plot_ambiguity_decomp.py
#    deps:
#      - decomps
#      - ../../plot_ambiguity_decomp.py
#    outs:
#      - plots/ambiguity_decomp

# deprecated, now part of plot_bvd -- should still work though
#  dataset_summary:
#    matrix:
#      dataset: ${datasets}
#    cmd: python ../../dataset_summary.py --dataset ${item.dataset}
#    deps:
#      - ../../dataset_summary.py
#    outs:
#      - plots/dataset_summary/${item.dataset}.yaml

