#file: noinspection YAMLSchemaValidation
vars:
  - models:
      - standard_rf
      - drf_weighted_bootstrap
      - drf_weighted_fit
      - xu_chen
      - capped_sigmoid
      - capped_lerped_sigmoid
#      - ensemble-weighted-classifier
#      - diversity-effect-weighted-classifier
  - slow_models:  # TODO
      - dynamic_threshold
#      - drf_weighted_fit_oob
  - small_datasets:
      - qsar-biodeg
      - diabetes
  - medium_datasets:
      - digits
      - bioresponse
      - spambase-openml
  - large_datasets:
      - mnist_subset
      - cover

stages:


  train_small:
    matrix:
      model: ${models}
      dataset: ${small_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_small:
    matrix:
      model: ${models}
      dataset: ${small_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  train_medium:
    matrix:
      model: ${models}
      dataset: ${medium_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_medium:
    matrix:
      model: ${models}
      dataset: ${medium_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  train_large:
    matrix:
      model: ${models}
      dataset: ${large_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_large:
    matrix:
      model: ${models}
      dataset: ${large_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/


  train_slow_small:
    matrix:
      model: ${slow_models}
      dataset: ${small_datasets}
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl


  get_staged_decomp_values_slow_small:
    matrix:
      model: ${slow_models}
      dataset: ${small_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/


  train_slow_medium:
    matrix:
      model: ${slow_models}
      dataset: ${medium_datasets}
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl


  get_staged_decomp_values_slow_medium:
    matrix:
      model: ${slow_models}
      dataset: ${medium_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/


  train_slow_large:
    matrix:
      model: ${slow_models}
      dataset: ${large_datasets}
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl


  get_staged_decomp_values_slow_large:
    matrix:
      model: ${slow_models}
      dataset: ${large_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  plot_bvd_decomps:
    cmd: python ../../plot_bvd.py
    deps:
      - staged-decomp-values
      - ../../plot_bvd.py
      - ../../../decompose/plot_decomp_grid.py
    outs:
      - plots/bvd-decomps/plot_bvd_drf
      - plots/bvd-decomps/plot_bvd_standard_rf

# TODO re-enable
#  plot_ens_decomps:
#    cmd: python ../../plot_ens.py
#    deps:
#      - staged-decomp-values
#      - ../../plot_ens.py
#    outs:
#      - plots/bvd-decomps/ens.png

  plot_margin_distr_by_trees:
    cmd: python ../../plot_margins.py
    deps:
        - staged-decomp-values
        - ../../plot_margins.py
    outs:
      - plots/margins/

  plot_margin_hists:
    cmd: python ../../plot_margin_hists.py
    deps:
        - staged-decomp-values
        - ../../plot_margin_hists.py
    outs:
      - plots/margin_hists/

# TODO add plot_err_div

  plot_compare_models:
    cmd: python ../../plot_compare_models.py
    deps:
      - staged-decomp-values
      - ../../plot_compare_models.py
    outs:
      - plots/compare_models/


