#file: noinspection YAMLSchemaValidation
vars:
  - faster_models:
      - standard-rf-classifier
      - drf-weighted-bootstrap-classifier
      - drf-good-weighted-bootstrap-classifier
      - drf-weighted-fit-classifier
      - sigmoid-weighted-bootstrap-classifier
      - xuchen-weighted-bootstrap-classifier
#      - ensemble-weighted-classifier
#      - diversity-effect-weighted-classifier
  - all_models:
      - standard-rf-classifier
      - drf-weighted-bootstrap-classifier
      - sigmoid-weighted-bootstrap-classifier
      - xuchen-weighted-bootstrap-classifier
      - drf-weighted-fit-classifier
      - drf-weighted-fit-oob-classifier  # slow!
  - small_datasets:
      - qsar-biodeg
      - diabetes
  - medium_datasets:
      - digits
      - bioresponse
      - spambase-openml
  - large_datasets:
      - mnist_subset
      - cover
  - all_datasets:
      - qsar-biodeg
      - diabetes
      - digits
      - bioresponse
      - spambase-openml
      - mnist_subset
      - cover

stages:

  # hack to mark all with this model as changed, remove
#  train_sigmoid:
#    matrix:
#      dataset: ${medium_datasets}
#    cmd: python ../../run_bvd.py --model sigmoid-weighted-bootstrap-classifier --dataset ${item.dataset}
#    deps:
#      - ../../run_bvd.py
#    params:
#      - params.yaml:
#      - params-sigmoid.yaml:
#    outs:
#      - results/${item.dataset}/sigmoid-weighted-bootstrap-classifier.pkl
#      - decomps/${item.dataset}/sigmoid-weighted-bootstrap-classifier.pkl


  train_small:
    matrix:
      model: ${all_models}
      dataset: ${small_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_small:
    matrix:
      model: ${all_models}
      dataset: ${small_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  train_medium:
    matrix:
      model: ${all_models}
      dataset: ${medium_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_medium:
    matrix:
      model: ${all_models}
      dataset: ${medium_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  train_large:
    matrix:
      model: ${faster_models}
      dataset: ${large_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_large:
    matrix:
      model: ${faster_models}
      dataset: ${large_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

# deprecated, to be replaced with things from get_staged_decomp_values
#  plot_staged_errors:
#    cmd: python ../../plot_staged_errors.py
#    deps:
#      - results
#      - ../../plot_staged_errors.py
#    outs:
#      - plots/staged_errors/


  plot_bvd_decomps:
    cmd: python ../../plot_bvd.py
    deps:
      - staged-decomp-values
      - ../../plot_bvd.py
    outs:
      - plots/bvd-decomps/bvd.png

  plot_ens_decomps:
    cmd: python ../../plot_ens.py
    deps:
      - staged-decomp-values
      - ../../plot_ens.py
    outs:
      - plots/bvd-decomps/ens.png

  plot_compare_models:
    matrix:
      dataset: ${all_datasets}
    cmd: python ../../plot_compare_models.py --dataset ${item.dataset}
    deps:
      - staged-decomp-values
      - ../../plot_compare_models.py
    outs:
      - plots/bvd-decomps/${item.dataset}/



# deprecated
#  plot_ambiguity_decomp:
#    cmd: python ../../plot_ambiguity_decomp.py
#    deps:
#      - decomps
#      - ../../plot_ambiguity_decomp.py
#    outs:
#      - plots/ambiguity_decomp

# deprecated, now part of plot_bvd -- should still work though
#  dataset_summary:
#    matrix:
#      dataset: ${datasets}
#    cmd: python ../../dataset_summary.py --dataset ${item.dataset}
#    deps:
#      - ../../dataset_summary.py
#    outs:
#      - plots/dataset_summary/${item.dataset}.yaml

