#file: noinspection YAMLSchemaValidation
vars:
  - models:
      - standard_rf
      - drf_weighted_bootstrap
      - drf-weighted-fit
      - xu_chen
      - capped_sigmoid
      - capped_lerped_sigmoid
      - dynamic_threshold
#      - ensemble-weighted-classifier
#      - diversity-effect-weighted-classifier
  - slow_models:  # TODO
      - drf_weighted_fit_oob
  - small_datasets:
      - qsar-biodeg
      - diabetes
  - medium_datasets:
      - digits
      - bioresponse
      - spambase-openml
  - large_datasets:
      - mnist_subset
      - cover
  - all_datasets:
      - qsar-biodeg
      - diabetes
      - digits
      - bioresponse
      - spambase-openml
      - mnist_subset
      - cover
  - binary_datasets:
      - qsar-biodeg
      - diabetes
      - bioresponse
      - spambase-openml

stages:

  # hack to mark all with this model as changed, remove
#  train_sigmoid:
#    matrix:
#      dataset: ${medium_datasets}
#    cmd: python ../../run_bvd.py --model sigmoid-weighted-bootstrap-classifier --dataset ${item.dataset}
#    deps:
#      - ../../run_bvd.py
#    params:
#      - params.yaml:
#      - params-sigmoid.yaml:
#    outs:
#      - results/${item.dataset}/sigmoid-weighted-bootstrap-classifier.pkl
#      - decomps/${item.dataset}/sigmoid-weighted-bootstrap-classifier.pkl

  # okay so my "good drf" thing is *not* a special case of binary with fixed threshold at 1/2
  # so we can't kill two birds with one stone here
  # -- evaluating with fixed threshold most likely only makes sense on binary classification problems since
  # equivalence (correct/incorrect) is not given there
  # -- evaluating with dynamic threshold is also different for binary, should evaluate these on all datasets


  train_small:
    matrix:
      model: ${models}
      dataset: ${small_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_small:
    matrix:
      model: ${models}
      dataset: ${small_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  train_medium:
    matrix:
      model: ${models}
      dataset: ${medium_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_medium:
    matrix:
      model: ${models}
      dataset: ${medium_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  train_large:
    matrix:
      model: ${models}
      dataset: ${large_datasets}  # only difference
    cmd: python ../../run_bvd.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - ../../run_bvd.py
      - ../../../decompose/models/${item.model}.py
    params:
      - params.yaml:
    outs:
      - results/${item.dataset}/${item.model}.pkl
      - decomps/${item.dataset}/${item.model}.pkl

  get_staged_decomp_values_large:
    matrix:
      model: ${models}
      dataset: ${large_datasets}
    cmd: python ../../get_staged_decomp_values.py --model ${item.model} --dataset ${item.dataset}
    deps:
      - decomps/${item.dataset}/${item.model}.pkl
      - ../../get_staged_decomp_values.py
    outs:
      - staged-decomp-values/${item.dataset}/${item.model}/

  # introducing DRF, XuChen:
  # [standard-rf-classifier, drf-weighted-bootstrap-classifier, xuchen-weighted-bootstrap-classifier]
  # ~> does not improve avg member error, improves diversity
  # ~> should actually only apply to binary but can still run and evaluate for multiclass

  # should cap at threshold -> sigmoid
  # [standard-rf-classifier, drf-weighted-bootstrap-classifier, sigmoid-weighted-bootstrap-classifier (without lerping b)]
  # spike ~> capped lerped sigmoid

  # multiclass
  # [standard-rf-classifier, drf-good-weighted-bootstrap-classifier (rename)]


  plot_bvd_decomps:
    cmd: python ../../plot_bvd.py
    deps:
      - staged-decomp-values
      - ../../plot_bvd.py
    outs:
      - plots/bvd-decomps/bvd.png

  plot_ens_decomps:
    cmd: python ../../plot_ens.py
    deps:
      - staged-decomp-values
      - ../../plot_ens.py
    outs:
      - plots/bvd-decomps/ens.png

# just because im too tired to wait, re-enable
#  plot_compare_models:
#    matrix:
#      dataset: ${all_datasets}
#    cmd: python ../../plot_compare_models.py --dataset ${item.dataset}
#    deps:
#      - staged-decomp-values
#      - ../../plot_compare_models.py
#    outs:
#      - plots/bvd-decomps/${item.dataset}/



# deprecated
#  plot_ambiguity_decomp:
#    cmd: python ../../plot_ambiguity_decomp.py
#    deps:
#      - decomps
#      - ../../plot_ambiguity_decomp.py
#    outs:
#      - plots/ambiguity_decomp

# deprecated, now part of plot_bvd -- should still work though
#  dataset_summary:
#    matrix:
#      dataset: ${datasets}
#    cmd: python ../../dataset_summary.py --dataset ${item.dataset}
#    deps:
#      - ../../dataset_summary.py
#    outs:
#      - plots/dataset_summary/${item.dataset}.yaml

