bvd_config:
  loss: squared
  parameter_name: n_estimators
  parameter_values: [150]
  save_decompositions: false
  trials_progress_bar: true

run_experiment_config:
  n_trials: 3

data:
  frac_training: 0.75
