bvd_config:
  loss: cross_entropy
  parameter_name: n_estimators
  parameter_values: [10]
  save_decompositions: true
  trials_progress_bar: true

run_experiment_config:
  n_trials: 3

data:
  frac_training: 0.75


plot_bvd_getters:
  - get_expected_ensemble_loss
  - get_average_bias
  - get_average_variance
  - get_diversity

plot_ens_getters:
  - get_expected_ensemble_loss
  # TODO think I still need to implement others for regression case
